### ISSUE TITLE
OMSA8 has no srvadmin-rac[45] package

### ISSUE THREAD

**Issue by jschaeff** [vide/puppet-omsa#4]
Hi,

this module won't work on debian jessie, as the OMSA version is 8 and there is no more srvadmin-rac5 package.
I'm not sure which package has replaced it. I can see srvadmin-idracadm8 or idrac7

The thing is, how can we get the idrac version that we should install ?

**Comment by vide** [comment]
Hi

thanks for the report, I'll give it a look in the next days to both Debian and CentOS (but I think I've updated to OMSA 8 some CentOs and had no problem at all)

**Comment by vide** [comment]
@jschaeff could you please check if the `development` branch fixes your issue?

**Comment by jschaeff** [comment]
Hi,

thank you, I tested on a Debian 8 server and it works ! 

I don't have any Debian9 ready server to test it for the moment 😃
